apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secretkv
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: secretkv
    type: Opaque
    data:
    - objectName: "secretkv"
      key: secretkv
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "$KV"
    objects: |
      array:
        - |
          objectName: "secretkv"
          objectType: secret
    tenantId: "$AZURE_TENANT_ID"